pluginsGLPI/escalade

ajax/user_values.php, inc/group_group.class.php, scripts/filtergroup.js.php
When assigned group filter is enable, only assigned groups users should be assignable on the ticket
=> Add assigned user filtering

js/remove_btn.js.php, setup.php
Adding problem and change handling in actors button removal feature. Removing limitation on "group_ticket" check in conditional inclusion of JS file.
=> Fixing issue #44

inc/ticket.class.php
=> fix: bad resolved notification when tickets are linked

escalade.xml
Added short and long description as well as language code and tags in Czech language. Sorted alphabetically to correct displaying order on plugins.glpi-project.org
=> l10n – added Czech translation into xml data

escalade.xml
Revised list of languages to present translations, that are at least from 50% done on Transifex (to don't confuse users about true availability in their languages).
=> Tweaked escalade.xml

ajax/group_values.php, escalade.xml, hook.php, inc/group_group.class.php, inc/history.class.php, inc/notification.class.php, inc/ticket.class.php, setup.php
- Use ITILFollowup in replacement of TicketFollowup
- Use array conditions instead of string in CommonDBTM::find()
- Use array conditions instead of string in Dropdown::show()
=> GLPI 9.4 compatibility

inc/config.class.php, inc/user.class.php, js/filtergroup.js.php
Fix JS to filtering group
according to #73
=> JS for group filtering

inc/history.class.php
I'm not 100% sure about this but "Climbed" sounds funny when talking about tickets.
I think 'Escalated" may be the correct term for this.
=> Fix labels (climbed -> escalated)

js/remove_btn.js.php
The plugin allow to prevent actor deletion : 
The goal is to ensure that at least one actor is set on the ticket.
The prevention is done by deleting the "delete" action.
Here we can't remove the assigned group for example:
However, it is still possible to delete the group by pressing backspace in the input.
To avoid this I've added a `required` prop to the select, making sure no user can bypass the check and send empty data (well they can still edit the html as we don't have a backend check but I don't think its a big issue).
The previous code was executed 21 times every 0.5 seconds to take into account the ticket creation time, I've simplified it a bit by not running the `removeDeleteButtons` function again if the target itemtype/actor was already handled sucessfully.
!27590
=> Fix non-deletable actors

CHANGELOG.md, inc/ticket.class.php
Errors during cloning were not displayed
ref !32095
=> fix(clone): error display

hook.php
Linked PR : https://github.com/pluginsGLPI/escalade/pull/204
=> Add config table column for plugin update to 2.9.7

inc/config.class.php, locales/en_GB.po, locales/escalade.pot
**UPDATED**
a time of creation -> at creation time
a time of modification -> at modification time
**ADDED**
Assign me as observer by default
=> Fix(Locales): update bad msgid

inc/history.class.php
=> Fix Display icon on History

.github/workflows/locales-sync.yml, .github/workflows/locales-update-source.yml
Implement translate CI
Waiting for : https://github.com/glpi-project/plugin-translation-workflows/pull/2
=> Feat(build):  implement translate CI

.github/workflows/locales-sync.yml
=> Fix(Build): exclude Saturday and Sunday

front/ticket.form.php
Fix an error when escalating a ticket ($track is undefined).
=> Bugfix redirect message when escalating ticket

.github/pull_request_template.md
Add the update of the CHANGELOG in the checklist, as it is almost systematically requested.
=> add changelog update to checklist

composer.json, composer.lock, front/config.form.php, hook.php, inc/config.class.php, inc/group_group.class.php, inc/history.class.php, inc/ticket.class.php, inc/user.class.php, phpstan.neon, setup.php
=> phpstan level 5

CHANGELOG.md, inc/ticket.class.php, tests/units/TicketTest.php
Fixed cloned ticket closing when linked ticket is closed when the option `Close cloned tickets at the same time`) is enabled.
=> Fix close cloned tickets at the same time

CHANGELOG.md, hook.php, inc/config.class.php, inc/ticket.class.php
- It fixes !36345
Completes https://github.com/pluginsGLPI/escalade/pull/234 which deals with the case where ‘Ticket status after an escalation’ = to a status, but not if it is equal to ‘Don't change’.
=> fix status after escalation

CHANGELOG.md, inc/ticket.class.php
- It fixes !36732
The option to change staut after escalation no longer works
=> Fix change status after escalation

ajax/assign_me.php, front/climb_group.php, front/config.form.php, front/group_group.form.php, front/popup_histories.php, front/ticket.form.php, front/user.form.php
=> Fix: front/ check

CHANGELOG.md, front/ticket.form.php
=> fix: 8 warnings in php-errors.log file

CHANGELOG.md, ajax/cloneandlink_ticket.php, inc/config.class.php
- It fixes !38425
- Rename close_linkedtickets option
=> fix(config): rename close_linkedtickets option in config interface
