- inc/ticket.class.php
Hello,
There is conflicts with escalations, formcreator and behavior (I think), steps to reproduce : 
- Behavior      : take first group of technician
- Escalation    : delete technicians on escalation
- Formcreator : in ticket target, set the assigned technician to form requester
Escalation remove current assigned technician if the first action in current backtrace isn't ticket add method, but when you submit a form, the first action is saveform, but you are indeed creating a ticket.
This PR solve this problem.
> Check if current backtrace is ticket creation context, fixing formcreator conflict

- inc/ticket.class.php
Refactor form duplication for better maintainability and testing
Fix PHP warning 
This commit 5d17a33 cleaned up the call to backtrace, but the cleanup was not finished, a little further there was another call to $ first_trace
Closes #68
> fix(core): fix undefined variable

- hook.php
- inc/history.class.php
- inc/ticket.class.php
Hello,
I want to add some informations in escalation history table :
Previous group assigned (Group A)
Counter of escalations between Group A (previous) and Group B (new assigned group)
New search option : total number of escalations in one ticket
New search option : total number of escalations in one ticket between 2 distincts groups
> Improve history table with previous_groups_id field and counter field

- inc/config.class.php
To reproduce :
- install and activate plugin,
- enable filtering on the groups assignment:
- call `cron.php` using CLI.
> Fix undefined 'glpiID' on CLI call; fixes #78

- hook.php
- inc/ticket.class.php
When group is added to ticket,
plugin automatically remove old group, notification about new group assign is send to both.
1. An assign group is added to ticket
2. GLPI add group
3. GLPI sen dnotification about new group assign (send to both)
4. Plugin remove old group
this PR fix this
When a group is added, plugin is called from ```pre_item_add``` hook (on Group_Ticket) before add group
At this point this fix disabled notification ```$item->input['_disablenotif'] = true;```
When group is definitely added  (in DB) plugin is called from ```item_add``` hook
Plugin send notification about new group assign
> fix(core): do not notify old group

- inc/history.class.php
- js/central.js.php
Javascript change in https://github.com/glpi-project/glpi/pull/12953 impact this plugin.
Also another PR removed the `col-xxl-4` class so it should be remove from the plugin too.
Before:
After: 
Rather than creating a new layout, I've used masonry's `appended` method which is designed to handle this case.
> Fix group view

- inc/user.class.php
`$key` does not exist. It should be `$id`.
> Fix logging of use_filter_assign_group ma failure

- inc/ticket.class.php
prevent reopening ticket on solve
(reopening because escalation plugin take first assign group to assign it to ticket after solved him)
fix : !28523
> fix(solve) : prevent reopening ticket on solve

- inc/ticket.class.php
- templates/escalade_form.html.twig
!30933
This PR fixes an issue in the escalation process where all groups were being shown in the escalation task, regardless of the filtering rules in place. The expected behavior is that only the groups specified in the filtering rules should be available for escalation.
- Added logic in `PluginEscaladeTicket::showForm` to get the filtered groups and pass them to the template.
- Updated the `escalade_form.html.twig` template to use the filtered groups for the 'condition' field.
> fix: correct group filtering in escalation process

- inc/ticket.class.php
This PR fixes a display issue in the timeline footer of a ticket. When the action button is split into multiple buttons, instead of its dropdown form, the button was displayed without a label, only with its icon. This fix ensures that a short label is displayed for the button.
- Added a 'short_label' to the action button configuration in `PluginEscaladeTicket` class.
> fix: add short label to split action buttons in timeline footer

- inc/ticket.class.php
- templates/escalade_form.html.twig
Fix group dropdown depending on the configuration 'use_filter_assign_group'
> Fix group dropdown in escalate form

- inc/group_group.class.php
- setup.php
This PR follows on from PR #165, which aims to solve a problem related to the groups available for escalation.
Currently, when the "Enable filtering on assignment groups" option is set to "Yes" and the "Override filtering when assigning groups" field is set to "No" in the user configuration, all the user's and ticket's groups, as well as the groups configured for escalation in each, are available for escalation.
The expected behavior is to have only those groups authorized by the group(s) currently assigned to the ticket.
> fix: correct group assignment logic

- CHANGELOG.md
- front/ticket.form.php
- inc/ticket.class.php
Replace https://github.com/pluginsGLPI/escalade/pull/158
Fix behavior for ```Ticket status after an escalation```	
```Do not Change``` and other status are apllied.
The final problem concerns ```SLAs```
When status is  ```new``` the ```take into account is computed``` (they shouldn't be). 
Should fix : internal ref : 30921 and #93
> fix(Core): fix behavior from 'status' option

- inc/ticket.class.php
Fix ticket status when user is assign (should be  ```Processing```)
Fix : https://github.com/pluginsGLPI/escalade/issues/93#issuecomment-1988519267
> fix(Core): fix ticket status when user is assign (-> Processing)

- CHANGELOG.md
- inc/group_group.class.php
- setup.php
Revert to old group filtering behaviour
Bug introduced by https://github.com/pluginsGLPI/escalade/pull/167
This PR fix current behavior while fixing the problem on #167
should fix #173, #171, internal ref 31866, internal ref 31926, internal ref 31951
> Fix(Group filtering): Revert to old group filtering behaviour

- .github/workflows/continuous-integration.yml
- .phpcs.xml
- ajax/assign_me.php
- ajax/central.php
- ajax/cloneandlink_ticket.php
- ajax/history.php
- composer.json
- composer.lock
- front/climb_group.php
- front/config.form.php
- front/group_group.form.php
- front/popup_histories.php
- front/ticket.form.php
- front/user.form.php
- hook.php
- inc/config.class.php
- inc/group_group.class.php
- inc/history.class.php
- inc/notification.class.php
- inc/ticket.class.php
- inc/user.class.php
- js/central.js.php
- js/cloneandlink_ticket.js.php
- js/escalade.js.php
- js/remove_btn.js.php
- phpstan.neon
- setup.php
> Phpcs + PHPstan

- CHANGELOG.md
- inc/ticket.class.php
Escalade allows the deletion of technician groups assigned to tickets despite the _**Show delete button**_ option being set to **No** in the plugin configuration.
Related ticket : 32414
> Add post update processing to prevent unauthorized deletion of ticket actors

- CHANGELOG.md
- inc/ticket.class.php
When the option "Delete old groups when adding a new group" is set to "No" and the ticket is escalated, the 'assign_group' event notification is not sent
Related ticket : 32782
> Fix unsended notifications while 'Delete old groups when adding a new one' is set to 'No'

- escalade.xml
Due to this -> https://github.com/pluginsGLPI/escalade/pull/184
Since version 2.9.5, the plugin is only compatible with GLPI version 10.0.11.
But ```plugin.xml``` indicates compatibility with all versions of GLPI 10.0.x
fix : #193
> fix GLPI compatibility

- inc/ticket.class.php
Fixed systematic deletion of actors linked to a ticket.
Issue : https://github.com/pluginsGLPI/escalade/issues/190
> Fix auto deletion of actors to a ticket

- CHANGELOG.md
- inc/ticket.class.php
- js/remove_btn.js.php
It was possible to delete users from a ticket even when this was supposed to be blocked by the plugin's configuration. 
now the modification is logged in the backend as well as the front end
**Before**
**After**
> Prevent unselection of actors who cannot be removed

- inc/ticket.class.php
- js/remove_btn.js.php
With this option, the delete button on the actor is considered deleted when you try to delete it. However, ol is indicated in the configuration that the delete button is displayed for users assigned to the ticket, but not for groups.
**Before**
**After**
> Fix user deletion lock

- hook.php
- inc/config.class.php
- inc/ticket.class.php
- templates/escalade_form.html.twig
The customer requests that the “Assign me as observer” box be unchecked by default.
Related ticket : 33253
> Add option for assign as observer default value

- CHANGELOG.md
- inc/ticket.class.php
Fix ```use technician group``` option that no longer work on creation
```$ticket->input['_groups_id_assign']``` and ```$ticket->input['_users_id_assign']``` are now an array (checks must be carried out in different ways)
Fix : !33591
> Fix(Option): fix 'use technician group' option

- CHANGELOG.md
- front/ticket.form.php
- hook.php
- inc/ticket.class.php
- templates/escalade_form.html.twig
Business rules ticket are not applied when escalating to a new group.
Ticket : 33108
> Fix rules execution before escalation

- CHANGELOG.md
- inc/ticket.class.php
Related ticket : 33742 and 33767
Problem added by the PR : #200 
When a ticket is updated with fields that have nothing to do with the Escalade plugin, an escalation is triggered anyway.
> Fix climbing triggered when ticket is updated

- inc/ticket.class.php
Related ticket : 33695
Continuation of this PR : #212 
These two parameters in the configuration allow you to remove users from the actors in a ticket after an escalation. But this feature was no longer working.
> Fix users (tech & requester) not being deleted during escalation

- CHANGELOG.md
- front/climb_group.php
- front/popup_histories.php
- inc/history.class.php
- inc/ticket.class.php
Related ticket : 33695 and 33706
Escalation by history has been broken by this PR : https://github.com/pluginsGLPI/escalade/pull/200
Here is the assignment history : 
However, when climbing through this history, the following errors occur
The changes made to fix this problem have resulted in a change to the full history window to a modal:
Before : Window
After : Modal
> Fix climbing with history & update full history window

- inc/ticket.class.php
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !33742
Fixed the fact that the escalation history no longer appeared when the assigned groups were changed from the ticket form.
> Fix escalation history

- CHANGELOG.md
- inc/ticket.class.php
When using history to clib to specific group
related task is not added
nb : since https://github.com/pluginsGLPI/escalade/pull/200/files (bad copy paste)
> Fix task added from ajax climb

- CHANGELOG.md
- inc/ticket.class.php
trying to apply a status based on the `_from_assignment` key no longer works
I don't know if this is due to a change in GLPI or in the plugin (it's a pain to debug) but the easiest way is to change the status when we add an entry to the escalation history (which means we actually have an escalation).
> Fix(Core): Fix status after escalation

- CHANGELOG.md
- front/ticket.form.php
Do not add history (task) if ticket update failed (when mandatory fields not filled)
> Fix(Core): take care of mandatory field

- CHANGELOG.md
- front/ticket.form.php
- inc/ticket.class.php
- It fixes !35612
Better fix for https://github.com/pluginsGLPI/escalade/pull/253/files
Refactor code
Add `group_Ticket` instead of update `Ticket` (and get more than one notification
> Fix(Notification): better fix for double notification

- CHANGELOG.md
- inc/ticket.class.php
- tests/units/UserEscalationTest.php
- It fixes !35657
When we try to add several technicians to a ticket with the escalation plugin enabled and the Remove technician(s) on escalation option active, only 1 is assigned.
> Remove user deletion when we add more than one user

- CHANGELOG.md
- inc/ticket.class.php
- tests/units/GroupEscalationTest.php
- It fixes !35984
Fixed assignment of requester group to ticket. when the requester was changed, the group assigned to the ticket became that of the requester and not that of the technician.
> Fix wrong group assign to a ticket

- CHANGELOG.md
- inc/config.class.php
- inc/history.class.php
- inc/ticket.class.php
- js/remove_btn.js.php
- setup.php
- It fixes !35797
- This RP resolves the issue that the configuration of the Escalation module was saved in the $_SESSION with the 'plugins' key while most other plugins use the 'glpi_plugins' key. This posed an issue with, for example, the ApproveByMail plugin. If the user has rules that modify the group if a validation is accepted with ticket rules and he approves a validation with the ApproveByMail plugin, the old group is not deleted even if the configuration "Delete old groups when adding a new" of climb is set to "Yes".
> fix: rename $_SESSION key from 'plugins' to 'glpi_plugins'

- front/ticket.form.php
- inc/ticket.class.php
Use right session key
following https://github.com/pluginsGLPI/escalade/pull/282
> Fix(Core): use right session key

- CHANGELOG.md
- inc/ticket.class.php
- tests/units/GroupEscalationTest.php
- It fixes #36431
- This PR removes users during an escalation to a group if the option "Remove technicians during an escalation" is enabled
> fix: Remove the user when a ticket escalates to a group

- CHANGELOG.md
- hook.php
- It fixes !36789
Since https://github.com/pluginsGLPI/escalade/pull/291, when a user is created, this error appears in `sql-error.log`:
```
glpisqllog.ERROR: DBmysql::doQuery() in .../src/DBmysql.php line 395
*** MySQL query error:
SQL: INSERT INTO glpi_plugin_escalade_users (`users_id`, `use_filter_assign_group`)
VALUES (217023, 0)
Error: Unknown column 'use_filter_assign_group' in 'field list'
Backtrace :
marketplace/escalade/hook.php:476                  DBmysql->doQuery()
src/Plugin.php:1713                                plugin_escalade_item_add_user()
src/CommonDBTM.php:1404                            Plugin::doHook()
src/AuthLDAP.php:2955                              CommonDBTM->add() …
```
> fix: Bypass filtering on the groups assignment option

- CHANGELOG.md
- inc/ticket.class.php
- It fixes !36851
Ticket status remains new when a technician self-assigns to the ticket
> fix: status when self-assign

- CHANGELOG.md
- inc/ticket.class.php
- It fixes https://github.com/pluginsGLPI/escalade/issues/309
Prevent undefined index
```
[2025-03-19 12:07:51] glpiphplog.WARNING:   *** PHP Warning (2): Undefined array key "comment" in glpi/marketplace/escalade/inc/ticket.class.php at line 519
``` 
`$_POST['comment'] is uselesse here (it's a bad copy/past)`
> Fix(Core): prevent undefined index on climb

- CHANGELOG.md
- inc/ticket.class.php
- tests/units/GroupEscalationTest.php
- It fixes !36732
When using the escalation button to escalate the ticket to another group, the history function does not work.
> Fix history disapear when we use Escalate button

- hook.php
- inc/ticket.class.php
- tests/units/GroupEscalationTest.php
- It fixes !36974
- This PR fixes the bug that deleted the user during the assignment of his group when creating a ticket, when the option 'Use the technician’s group' was enabled.
> fix(group): user was deleted during ticket creation with use_assign_user_group enabled

- CHANGELOG.md
- front/ticket.form.php
- inc/ticket.class.php
- tests/EscaladeTestCase.php
- tests/bootstrap.php
- tests/units/TaskMessageTest.php
- tests/units/TicketTest.php
- It fixes !37622
- If the user uses the timeline button to escalate a group, ticket rules that take into account the technician field as a launch criterion are not executed.
> fix(ruleticket): Escalate timeline button execute RuleTicket

- CHANGELOG.md
- inc/ticket.class.php
- tests/units/TicketTest.php
- It fixes !37728
- If the ticket_last_status option is enabled in the escalation plugin configuration, and the user assigns himself to a ticket using the “Associate myself” button, the ticket status is modified to that configured. This behavior was not present in GLPI 9.5 and is also not present if the user is assigned to the ticket via the actor drop-down list.
> fix(ticket): assign myself button doesn't change ticket status when ticket_last_status option is enabled

- CHANGELOG.md
- inc/ticket.class.php
- tests/units/GroupEscalationTest.php
- tests/units/TicketTest.php
- tests/units/UserEscalationTest.php
- It fixes !37334
- If the option "remove a technician during an escalation" is activated and no group was assigned to the ticket, the technicians were not deleted. It's the same problem for "Assign Me" button.
Before escalation
After escalation
> fix: remove technician on ticket escalation if no group is assigned

- CHANGELOG.md
- front/ticket.form.php
- inc/notification.class.php
- inc/ticket.class.php
- setup.php
- tests/Units/GroupEscalationTest.php
- It fixes !37919 & !38152
When escalating a ticket to a new group, multiple notifications were being sent to all previously assigned groups instead of just notifying the newly assigned group.
Created two new notification target types:
- "Last group escalated in the ticket"
- "Manager of last group escalated in the ticket"
These targets specifically notify only the most recently added group during ticket escalation, preventing duplicate notifications to previously assigned groups.
> Fix - Duplicate notification sent to old group during escalation

- CHANGELOG.md
- inc/ticket.class.php
- tests/Units/GroupEscalationTest.php
- tests/Units/UserEscalationTest.php
- It fixes #368
- The plugin documentation specifies that only groups can escalate a ticket. This pull request therefore removes the ability for technicians to perform this action.
> fix(escalade): tech assignment should not trigger escalation behavior
